# Generated by Django 3.1.5 on 2021-01-11 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand name.', max_length=150, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name.', max_length=150, verbose_name='name')),
                ('main', models.ForeignKey(blank=True, help_text='Main category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', related_query_name='main_category', to='products.category', verbose_name='main category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('main_id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name.', max_length=350, verbose_name='name')),
                ('current_price', models.DecimalField(decimal_places=2, help_text='Product current price.', max_digits=10, verbose_name='current price')),
                ('raw_price', models.DecimalField(decimal_places=2, help_text='Product raw price.', max_digits=10, verbose_name='raw price')),
                ('likes_count', models.PositiveIntegerField(blank=True, default=0, help_text='Product likes count.', verbose_name='likes count')),
                ('discount', models.PositiveIntegerField(blank=True, default=0, help_text='Product discount.', verbose_name='discount')),
                ('is_new', models.BooleanField(blank=True, default=True, help_text='Is the product new?', verbose_name='is new?')),
                ('model', models.CharField(help_text='Product model.', max_length=9, verbose_name='model')),
                ('url', models.URLField(blank=True, help_text='Product URL.', null=True, verbose_name='URL')),
                ('image_url', models.URLField(blank=True, help_text='Product image URL.', null=True, verbose_name='image URL')),
                ('brand', models.ForeignKey(help_text='Product brand.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', related_query_name='product', to='products.brand', verbose_name='brand')),
                ('category', models.ForeignKey(help_text='Product category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', related_query_name='product', to='products.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('category', 'brand'),
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, help_text='Variation color.', max_length=25, null=True, verbose_name='color')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Variation thumbnail URL.', null=True, verbose_name='thumbnail URL')),
                ('image_url', models.URLField(blank=True, help_text='Variation image URL.', null=True, verbose_name='image URL')),
                ('product', models.ForeignKey(help_text='Product variation.', on_delete=django.db.models.deletion.CASCADE, related_name='variations', related_query_name='variation', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'variation',
                'verbose_name_plural': 'variations',
                'ordering': ('product',),
            },
        ),
    ]
