# Generated by Django 3.1.5 on 2021-01-11 21:38

import json
from os import name

from django.db import migrations
from pathlib import Path

from django.db.models.query import QuerySet

from apps.products.models import *

DATA_FILENAME = 'data/men.json'

def load_data(apps, schema_editor):
    json_file = Path(__file__).parents[3] / DATA_FILENAME

    with open(str(json_file), encoding='utf-8') as data_file:
        objects = json.load(data_file)
        brand_set = {}
        category_set = {}
        category_set = {}
        for obj in objects['elements']:
            try:
                brand = obj['brand']
                category = obj['category']
                subcategory = obj['subcategory']
                if len(brand) > 0 and (not brand in brand_set):
                    brand_set[brand] = Brand.objects.create(name=brand)
                if not category in category_set:
                    category_set[category] = Category.objects.create(
                        name=category,
                        main=None
                    )
                if not subcategory in category_set:
                    category_set[subcategory] = Category.objects.create(
                        name=subcategory,
                        main=category_set[category]
                    )
                product = Product.objects.create(
                    id=obj['id'],
                    name=obj['name'],
                    brand=brand_set.get(brand, None),
                    category=category_set[subcategory],
                    current_price=obj['current_price'],
                    raw_price=obj['raw_price'],
                    likes_count=obj['likes_count'],
                    discount=obj['discount'],
                    is_new=obj['is_new'],
                    model=obj['model'],
                    url=obj['url'],
                    image_url=obj['image_url']
                )
                variation_0_color = str(obj['variation_0_color'])
                if len(variation_0_color) > 0:
                    variation_0_thumbnail = obj['variation_0_thumbnail'] if len(obj['variation_0_thumbnail']) > 0 else None
                    variation_0_image = obj['variation_0_image'] if len(obj['variation_0_image']) > 0 else None
                    Variation.objects.create(
                        product=product,
                        color=variation_0_color[:20],
                        thumbnail_url=variation_0_thumbnail,
                        image_url=variation_0_image,
                    )
                variation_1_color = str(obj['variation_1_color'])
                if len(variation_1_color) > 0:
                    variation_1_thumbnail = obj['variation_1_thumbnail'] if len(obj['variation_1_thumbnail']) > 0 else None
                    variation_1_image = obj['variation_1_image'] if len(obj['variation_1_image']) > 0 else None
                    Variation.objects.create(
                        product=product,
                        color=variation_1_color[:20],
                        thumbnail_url=variation_1_thumbnail,
                        image_url=variation_1_image,
                    )
            except KeyError :
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
